insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Zontrax', 'morbi quis tortor', 3, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Keylex', 'odio donec vitae nisi nam', 1, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Flexidy', 'cras in purus eu', 3, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Job', 'arcu adipiscing molestie hendrerit', 3, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Span', 'lacus morbi quis tortor id', 4, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Sonsing', 'eleifend donec ut dolor', 3, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Tin', 'lacinia nisi venenatis', 5, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Fintone', 'maecenas pulvinar lobortis est', 4, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Namfix', 'volutpat erat quisque erat', 2, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Cookley', 'maecenas tristique est et', 4, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Temp', 'justo nec condimentum neque', 1, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Latlux', 'vestibulum ante ipsum', 2, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Bamity', 'praesent lectus vestibulum quam sapien', 2, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Fixflex', 'justo lacinia eget tincidunt', 4, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Tres-Zap', 'vivamus vel nulla eget', 1, 1);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Zontrax', 'mi in porttitor', 3, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Cookley', 'donec odio justo sollicitudin', 4, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Tresom', 'luctus rutrum nulla tellus in', 4, 0);
insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Alphazap', 'gravida nisi at nibh in', 3, 0);
	insert into Cursos (Nombre, Descripcion, NroCreditos, Activo) values ('Otcom', 'odio curabitur convallis duis consequat', 1, 1);